version: '3'
services: 
  repo-cache.dev:
      build:
        context: ../containers/repo-cache
        args:
          - OS_VER=${OS_VER}
          - HDP_VER=${HDP_VER}
          - AMBARI_VER=${AMBARI_VER}
          - HDP_UTILS_VER=${HDP_UTILS_VER}
          - AMBARI_STACK=${AMBARI_STACK}
          - REPO_HOST_ADDRESS_LOCAL=${REPO_HOST_ADDRESS_LOCAL}
        dockerfile: Dockerfile
      image: hdp/repo-cache
      hostname: repo-cache
      domainname: dev
      networks:
            dev:
              aliases:
                  - repo-cache
      ports:
        - "8085:80"

networks:
  dev:
    driver: bridge
